name: platepal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  video_player: ^2.6.1
  chewie: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/platepal_icon.png"
  adaptive_icon_background: "#FFFFFF" # You can change this color
  adaptive_icon_foreground: "assets/icons/platepal_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/platepal_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/platepal_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/platepal_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/
    - assets/ingredients/
    - assets/db/

    # Author of the app : Good luck with your project